# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  internal_url: https://hass.${SECRET_DOMAIN}

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.42.0.0/16
    - 192.168.0.0/16

recorder:
  db_url: !env_var HASS_RECORDER_DB_URL

wake_on_lan:

automation: []
script: []
scene: []
