# Loads default set of integrations. Do not remove.
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.42.0.0/16
    - 192.168.0.0/16

recorder:
  db_url: !env_var HASS_RECORDER_DB_URL

openid:
    client_id: ${HOME_ASSISTANT_AUTHENTIK_CLIENT_ID}
    client_secret: ${HOME_ASSISTANT_AUTHENTIK_CLIENT_SECRET}
    configure_url: "https://auth.${SECRET_DOMAIN}/application/o/home-assistant/.well-known/openid-configuration"
    scope: "openid profile email"
    username_field: "preferred_username"
    block_login: false

wake_on_lan:

automation: []
script: []
scene: []
