# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: authentik-secret
stringData:
  #ENC[AES256_GCM,data:LRg0g9oFd+1zMSn8QSs=,iv:NYKiXjYod9RkFrXQMukIv6ufAZ6/bQ+az8I5/7/x2gI=,tag:/up7EnvYlfeGSLblrm+b/g==,type:comment]
  AUTHENTIK_REDIS__DB: ENC[AES256_GCM,data:Sw==,iv:lIRZSGZdu60VUpZxotXxJAXpY/VfWJjSNGwG6yDSikY=,tag:jS0yw4NwkekWb7qWQmpisg==,type:str]
  AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:D51vkiAtYOwalTpmIRRnLe7Rjx3hTMNs1UsTt9FB,iv:tVcrKLw1Jx6QAOzYleuwe73tbojiAmvW1jVNWKWUC4I=,tag:AeZSjatc59z1RhqsEo4i8w==,type:str]
  #ENC[AES256_GCM,data:iMs2zni3ovyFyMdFJZLbHwNTM0oQBHTOmR8Htc75zCI=,iv:VnH+W4J9KAUkAUQiU1MuFKmvVG7m9S1Z661pzaRAZ3M=,tag:xYHhx71PkdozzwLtH/w0Gg==,type:comment]
  AUTHENTIK_LISTEN__LDAPS: ENC[AES256_GCM,data:j3a/hnryCb4EiDqw,iv:hbIA/dyQ+eoJt1lq7pSKVFLQ314tldIsh2CVp/I5F64=,tag:3Osi+lz1qfQjstMVt4yujA==,type:str]
  AUTHENTIK_LDAP__TLS_CIPHERS: ENC[AES256_GCM,data:01Qkh8EHs29QCg1OAMf2dru/kkvyPl1Fdlpf8zQqSzlSExo/RaBF8lq8dCom8IBanPFj2iUvOYWLpNDn6Oy3PG9+6iQ=,iv:sA6UpH+srdVIfbPEMGMmhoGU+yeUJBmoCTzdy4DzUwE=,tag:xwYoBZE3ofKSin5akXYJeA==,type:str]
  AUTHENTIK_LDAP__TLS__CERT: ENC[AES256_GCM,data:bdFCjj8iY3vTYIxI4SGCiDLn1A==,iv:xjqLpQpQxgKbq07C9O/7yhlE67Fwv+7Su+ec2bZdKbM=,tag:1pZ+ZjlC/vQIr7B2KT2AQw==,type:str]
  AUTHENTIK_LDAP__TLS__KEY: ENC[AES256_GCM,data:DR3hRJyAz6AxdV+iykqME2xObg==,iv:Ocj0kbc5tlapANJ3139II4RiGt/j6J4bvCdNxD93LJE=,tag:P7WGl5d+Y6ICeAGDvyuRWQ==,type:str]
  #ENC[AES256_GCM,data:dSvweEvkBc6loA==,iv:0U9DTxSDHjvEcj9Rb+5pTmoufKUiquLnMDR/cQuiaHQ=,tag:b8eNzL07+hPFO4uMrjxbsQ==,type:comment]
  AUTHENTIK_GRAFANA_CLIENT_SECRET: ENC[AES256_GCM,data:GedyFRcfGHk453oT7xw7kFih00SLB3Uhke/ioPzv4XjmT0RUE68kNCzYKw4316cxAQbWfu7qtp00CV4Tl+WdWsmdJZRh34CZ4S9Tmcrx+2elWDNwcQxTZzRJyi6xa257AL9mU08p9nPgYkIgqMDQuKWZLUuaXETBBiV8y1hiY+s=,iv:M76dGcJJmn6ZWzqvaJXHN2jMEdsnFl6Fl9p+mQ5U6uM=,tag:Cark68MOZqenU4d9HFenMQ==,type:str]
  AUTHENTIK_HOME_ASSISTANT_CLIENT_SECRET: ENC[AES256_GCM,data:8ukhuH7eLjbzc7IOSOnZuO2jpx3tGpuCUE04cyJy8kmlYwnGKoLyCDD3d8Yfi7zvkU+qqgwp/KPA8CbiI4fyOfJTtMEVeMgDXVK/zX2YoBOK5biQNVtN2EvhuYgnfDiGhbc+WV2RBR1v0x0Pr8waRznDDVJCs6/oQ3J4/uGqm48=,iv:hmAkSUlM7GkzPbb7u1eKLnmp0rkzypescnlUZeV5QQg=,tag:krMWdzdJWyry9mbjLGMEvw==,type:str]
  AUTHENTIK_IMMICH_CLIENT_SECRET: ENC[AES256_GCM,data:Iey83Dwd0jS8APzyVEVQWqq2E1RRnfOSrRv34BCsvE+LCvyVxXZ2DtAYGNCct08hAtgTrLA7zfTxS0GRVJX4t+C67JQbzbdDVv5BC9IE0xjtbVSDQlnGAbD2DIatqDHWLjFCUEf1z13sj5yt1UJbXZJZ+VzdVgk30saH20EHsgo=,iv:0xFTJO+tnxFEktbN75vTczwlbCgaH2HTkmsPQU39zEs=,tag:edIvyRsemZE7ZdooeFox8g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzY0V6RzBuT1RWc1hYaEo2
        bVQ3K0tnK2hSRE9XT0s0dU5tU1VwOUN0UGtnCjBja2RqaURQYWZxdHRiTXJPdzB0
        N0RwUENCb2JNdGgrK0xFUFhQcjRBVHcKLS0tIDI2SDNZVDV2d2JuT1FJd0Q4YWd4
        VGQ0SVhhaFhzeWRyajVVOFJzcWZSZEkKudJN8UtsRHeqZ2e/J7FPRLqgZv3lx1zh
        JGqjL4IYcoI8v9CTVn5/HFBexnmtXgNWaVz1cMXhAAEarpdE6UMHaA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sq0wjrxgd2p0kl55cl22306l3lyzt5n0hdmqny6tr9qfkwyxu3aszelc7a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-04T05:19:14Z"
  mac: ENC[AES256_GCM,data:Bj3aGdpt7ruCS88S1WZioyyoDrBRDwA638nNomczx0nvlzLk80G7kuouAKFceUdbQoxmhk5ak+rTbbdbF7zHSrNSY3hYmsqbQcOU6onwrwxh78ZzC3jkLBd/xeqWxHcUIOSlNfAO/2LfZuKBAbN9J/kHc3B0ctkJelqfro0ei1Y=,iv:7gVfMyrpCowsbsinKmI37L5ZKZjuj/5amh6Dig5CKvc=,tag:eyR8dOsMNgpg3N4J5HuokQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: authentik-db
stringData:
  username: ENC[AES256_GCM,data:kITUuxuptce+cXEngl5Wlb8W,iv:G/bu3BhrtHn75laOMsuzxhQTAm0eRTP73P62Xxr/syM=,tag:hghl1u7n8eN8OlXzYCY1Ag==,type:str]
  password: ENC[AES256_GCM,data:pIqvyV7nfjJ/Se30XMQ87IJpJUptCJ32KP+RvSNv,iv:lA8zqHm3CP8t0aRFk6ATcBlGfUkmHhGCoEN04DxoX8w=,tag:39HEKXn2gwPBvveq7tTV4A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzY0V6RzBuT1RWc1hYaEo2
        bVQ3K0tnK2hSRE9XT0s0dU5tU1VwOUN0UGtnCjBja2RqaURQYWZxdHRiTXJPdzB0
        N0RwUENCb2JNdGgrK0xFUFhQcjRBVHcKLS0tIDI2SDNZVDV2d2JuT1FJd0Q4YWd4
        VGQ0SVhhaFhzeWRyajVVOFJzcWZSZEkKudJN8UtsRHeqZ2e/J7FPRLqgZv3lx1zh
        JGqjL4IYcoI8v9CTVn5/HFBexnmtXgNWaVz1cMXhAAEarpdE6UMHaA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sq0wjrxgd2p0kl55cl22306l3lyzt5n0hdmqny6tr9qfkwyxu3aszelc7a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-04T05:19:14Z"
  mac: ENC[AES256_GCM,data:Bj3aGdpt7ruCS88S1WZioyyoDrBRDwA638nNomczx0nvlzLk80G7kuouAKFceUdbQoxmhk5ak+rTbbdbF7zHSrNSY3hYmsqbQcOU6onwrwxh78ZzC3jkLBd/xeqWxHcUIOSlNfAO/2LfZuKBAbN9J/kHc3B0ctkJelqfro0ei1Y=,iv:7gVfMyrpCowsbsinKmI37L5ZKZjuj/5amh6Dig5CKvc=,tag:eyR8dOsMNgpg3N4J5HuokQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
