# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: tautulli-secret
stringData:
  #ENC[AES256_GCM,data:WpyAqQPEO19SfeuBy0mK4y2I+Lh3/eclSQYjPRPxEeynuxSbWiQykzzcWAWlhc0IMCeeWqUSKiDfbxFkpAUIyD4r3g==,iv:/HAwv0gX7vBoEz2q7gdQIT+8fp0GkPsmPxfguW6dKn8=,tag:lR0KR2H8qNYWLYthO9mGPw==,type:comment]
  #ENC[AES256_GCM,data:a6QItY7xZ1CoLJ5l7CV4M5JcIJJQFmV9KBJ+5jAtFrvYcGuFX/DnnhcyjcoZVJ1UMO7OG9gAHJDzNB+REiyIXf0dgYRnZp+dboUo,iv:ksydrth3kZ3d1ZzUdgnR43+pUfGKNCsHbBMf1IiViP4=,tag:P6wpKL+29/cL6N0flrNVuw==,type:comment]
  TAUTULLI_API_KEY: ENC[AES256_GCM,data:F1LcyO8UtYrIXcXzEypiEZL+Zg9yk3iPHMnGk8YQVOo=,iv:cAqzECATD42r2fgyCjfkYwZRoPVAoVQxsGtsYywPrpI=,tag:yk/cx55PucLh1pdgJhr7YQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVXN3bTJQM2hwZjFJV09y
        REFNdnF4YXBBUGRDbjNUMk9Ea0lERjh1elVjCk5xR013dmt6enNXaHRqVmh1U2w2
        Z2w5b3o5U2RTQUwrS0s1WWZaRVB1S1kKLS0tIE5vR3l1R0w5RExBaFdsc2NVTC8z
        bEJSNFBwczU5Y3orckxyWUloRThmK2sKtZNBnOMLJyVheCalvBPqLqhJmjXh5AeQ
        7G0VQ99g+Sxcfwqb5+cyCCytca3a06u9nTzvnXnpPzseBC6pTAaxMg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sq0wjrxgd2p0kl55cl22306l3lyzt5n0hdmqny6tr9qfkwyxu3aszelc7a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-08T08:12:31Z"
  mac: ENC[AES256_GCM,data:GbO5X0tn/T2R0RoJIlIW6Vu6xu2ktvSpWA3zL1j8uofA3kBSvI/Y4BhAwR0/1CLDbVHpmMcGOdDeU9GrJmc4alm+9DI3IwsiiFNNJtbpYdxcZ5Tb3f7qJhS6GTBiaTlz2uFwNtAEl4b+3dzP2W0Iqqg5JQkFQPOgnoCgf49+iyQ=,iv:jQMak8hmdyHADhhNTmixtBjaaWyuPYI8h6ihWMxxx/Y=,tag:VMjFTAE99UzE3KM/B38vrQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
