# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:01txVHOmCNHa7jFNayz3bb4yd1KaReaj0xW4pg==,iv:XTYwXqNQ7AjsycF0NFs/z/DFW+p7Xy5AcAnLsQuR4+Q=,tag:jYxQ6Po7s2/P1+EOCAr7yQ==,type:str]
sops:
  age:
    - recipient: age1sq0wjrxgd2p0kl55cl22306l3lyzt5n0hdmqny6tr9qfkwyxu3aszelc7a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiU0x6c1hOQ2RkVVIycXFW
        Nk5ZdjUvaFBDVkVOTzBXbFM4RWd4bXArU2pJCmMxZkpBV0RGTWE0SFpvdnZGNTg1
        NkNuY1Y5ZVorbDZDY1lWRUNOQUdiMm8KLS0tIGhCTnJBSG5PYk4vWXo0cklTcmZ4
        VVcrU1VhbzdZZmgzdDhJVktocnI1UWMKHt0BQJ07YXxcRSoUaN0TBnkY0nhhIcVK
        bD6sB5hD0EtM9D2a6Q2UFkz8nfHX0m/D4CPae/ZalTYuvWH8v3lnfw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-14T21:09:59Z"
  mac: ENC[AES256_GCM,data:JjXVXOrpt3KsP9kY/Ao3EPViatBhdGChNxWQlQ8Dz/wyiTuLHf+j4Wrj2Yp41OHls2cdTIuq3k3gBqvaHGhiNN2+zzY6qUa+b71fS3YJMOufES8Cxts0406TtVyPhcUvkd1c79IDsKGHuefkiKpSjE/2nPQzEsvyLN10VKJKIAM=,iv:NCcMDqzWHcs61sUz/J5K9+HYp564D2Vy/PrF4Ksvp+4=,tag:nVoD6WqAaBVlgjNbx/Eg9Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
