# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: home-assistant-postgres
stringData:
  username: ENC[AES256_GCM,data:5g/HSc9WR447QnsTSQ==,iv:U7Al2h2Mz/XgGlecZ92QKt0i/1KPgjqQIgTvk+dGiGk=,tag:aPMvZagw9MQRggpguiWs1w==,type:str]
  password: ENC[AES256_GCM,data:o1Ugs0tlU1VfcitfIV5b8P/kTwMAyvDvwaYGfJ/XBLBZwcQkHGZ3Yyk0oQ==,iv:vc0DFZNIkq76Nwf3J24A6KocdqoJin8+LNV5sRlEm6A=,tag:tammEp4pG5TLEWNChOXWYg==,type:str]
  url: ENC[AES256_GCM,data:d6cIP64KiXupcec0paDDrctzHDHBjZxFwA8L3wpBsKxD/JLeBx58lzVblSEvfG7mehQYWCguahiqhef+Sl7xRXIvS0U75EQF+LypzMlWSF+MD7Jo1bV9GyM1Qw5/9M8FR5qHov/8SmBODzuxPo3xvbtxw2k+5/pHIaefXmJpWLnsT+QqSe3sbD0r/TgF,iv:ze4UyqrVPdezdRPBSF/EVAt1JXE7hA9h/uMFL+tAPD4=,tag:nyI3ngDnXQ/e/djG7YuPtQ==,type:str]
sops:
  age:
    - recipient: age1sq0wjrxgd2p0kl55cl22306l3lyzt5n0hdmqny6tr9qfkwyxu3aszelc7a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmaTJMQTZTTEhUZ0hneWsx
        Z0JYYU5RSGQ2bmZmSkV2alVLL0xZZUNLQm5RClhBNS9xVS9QMExGbnFLN0dwOXJL
        ZEZZbkNtd3AxZ0xOMTV2amF5VFhoWmcKLS0tIFdTc05zY2YvbnhHRU5POWd5QVBi
        V3A3d2Z2Z2t2WTBLRXRlYUR0bnQ5QzAKs8eA07nVtMlo8PIew0GnCs05BqXhgmRE
        2dms75L9yw2vEdTNe9pFDsCfYP60d9ziGx9FGiSt26NxjJb9KMyDwg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-05T05:40:04Z"
  mac: ENC[AES256_GCM,data:kYRO+FrNtnx5cNvvSb9asoer5MPMBSrMio78jCyBz9Vpyv6DNKXbALbNlg8bI6op5B07oySbd7Am8Z53lkv3XQzld62uearxFDfLchLDiJNc3A8JtbVTsg5Z3LhDTcJFy10WHbLlPiHcrKzZ+l4UPnkE+8/ihCtX5CAo5/o6kkY=,iv:TlXkxSdIoiIvk+dncCuak5sU5ZPThp1etLQtIm0fhiU=,tag:+jr/eWvJjOXhAyE+aJqxng==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
