# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: home-assistant-postgres
stringData:
  username: ENC[AES256_GCM,data:OfQl+ZV8hYr/DNuumF0=,iv:hPTUecRKQoQkm1iftLufKk/XeFuHE0ORd78TTWu3Atg=,tag:ze4DRTmYgIKgOsG9Xpgplg==,type:str]
  password: ENC[AES256_GCM,data:mEgVAPg1qezcacHZzDOH/XsHLwCyhrqydDh6Kg==,iv:Pkz3xi21VTMnFgK/me1bWHbs411eZu43bBAFUCfq2PA=,tag:o8kXzCqcameU9X6APMSUMg==,type:str]
  url: ENC[AES256_GCM,data:EiFOT5FPCtvox69x/XY9eMfepTDWD8GpHq5f2lkYlXbJB4ijP/+6MG9vwHw6Wg8y342jpxHCuxYoB43DHK+oRR1QQNf2w97DqH/6xeZ+EgqU303p18TPCBuek3nYJSPXXIwXzSasSMUFS0KT8PhDQoDH/+aBwYqLf3kXEFGSJFo=,iv:w41TwCGB2q/mpHAaDrfz+BcwdemQzfkn1tfyqeL8SWI=,tag:PhbCGCqu9ra8JigXL38s2A==,type:str]
sops:
  age:
    - recipient: age1sq0wjrxgd2p0kl55cl22306l3lyzt5n0hdmqny6tr9qfkwyxu3aszelc7a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTTlSQzJ4clRTYzFoQTN5
        aWVRaGpPblNhTDRqYk1LQmNIb3J3K29pZXl3CmpEcGhHcG12RzBnL2o0SVFVakpB
        c2VkM1BQRm1sU2JSRzlrYUYzNU9BRGcKLS0tIE9zSDQyamNOTWZ2TzliQmRpZEpL
        Z1ZvNGFmb1NmNzNrcnR1VCtaUk5vMkUK867iygTquW7/SvydBPtSSFZOgRSs/KNS
        nDPEWGAMCk6ELaDG+uQ9P9tX5ghr1hplHbFfSuzC+8a7d1S4Rkv/hw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-05T07:19:34Z"
  mac: ENC[AES256_GCM,data:AaCPEoLvLBZm7VsCkK77kuNd2wdk4Xt1qYx1gLJINCM7Eh8Pq+ltLmlZn+vy8Jv4J9ALMwBVrSNg+3G8rbp/3UmSMbcKJJdofHM385qYc8BomkGSLkpQr6WNTlKH2m/iVqNbpl07/0NEHWuOfyy+MjXC6TSXdsqbJXZ85LCK0HM=,iv:bRu21kINqw4GCT0fke3R8Nq/9NEp6uJ09TboXIijxXk=,tag:Dm462Fa5HfreXXDcZEyu7g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
