---
# yaml-language-server: $schema=https://flux.tholinka.dev/helmrelease/v2/github/cloudnative-pg/charts/main/charts/cloudnative-pg
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name cnpg
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *name
  driftDetection:
    mode: enabled
  install:
    strategy:
      name: RetryOnFailure
  upgrade:
    cleanupOnFail: true
    strategy:
      name: RemediateOnFailure
    remediation:
      remediateLastFailure: true
      retries: 2
  values:
    nodeSelector:
      kubernetes.io/arch: amd64
    crds:
      create: true
    monitoring:
      podMonitorEnabled: true
      grafanaDashboard:
        create: true