# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: kopia-secret
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: network,media,virtualization,authentication,database,self-hosted
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: network,media,virtualization,authentication,database,self-hosted
type: null
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:WljTZMt6jcAZwFoWxvK7fPMBdNDc9cve,iv:6NMWvxsX6POrdDy3HoKF6MUt6izK/iJBaWrB/gtBkYA=,tag:hlRjR+3zKdOSPLIQEKW2Tg==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:nltKE0L/wW2bMWML2VIrUy/zPKCRC6yq7yZqyA==,iv:EKtr05+o6eO6spFCbeJpfYj5iRu/ItUOVzES0eT1ob0=,tag:Wv0a5P+jH5oCDEjds7L6Ww==,type:str]
  KOPIA_LOG_LEVEL: ENC[AES256_GCM,data:Rw3sZq4=,iv:rq941GS5TaAs7nYTAzBHAtdRHRMDhfs3AJuMOicIUQ8=,tag:5eLeTE7ShGeBv0KJpGEGcA==,type:str]
sops:
  age:
    - recipient: age1sq0wjrxgd2p0kl55cl22306l3lyzt5n0hdmqny6tr9qfkwyxu3aszelc7a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIOWw3SnlnMUVuaG8xZ05R
        azhyRjZqb0g1SFNLK1lNUHNabG0vRTFqaFFnCkV1TVMvN3p4N0MvaHBsTlJYZDFm
        RHE4NHM5aWxkUHM2RWVpYVVFZStMSW8KLS0tIHlkTWhQcyttcHlWWllNVnhKMnFC
        MGk4N3JFR29LK3UyYUN4YnVRMmJta00KTg+IUB1sutezuyaKFvOsmJ33F6plfZcA
        ow9ES19ZUL51Rx8sazMM/y+QBYT4D1yPxhuk2LQj/TTbQohiWxOo3Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-19T07:02:48Z"
  mac: ENC[AES256_GCM,data:Ju0bJgdqBLXKlTTI4beCv6a3Qlkmz35243sf3mlXyUUGwBPlSuC003rEdtU1mVmqveDafdtfxsHHoDCO11pOxz8JtMVSpBAKGri4IEkrE2kz88N/GiexHHi1uSWgEdgD8su0mDEzr8BZbHEl8zpfbtbWVj2S5gnYH2Zv7ZZj7mQ=,iv:H+fsLt6bdxZr1kN4B+ZUMqsiySdE3cH2Cc+v5v3T2jg=,tag:fEB8vZ5LMnI/JZeO343+1A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
