# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: home-assistant-secret
stringData: null
sops:
  age:
    - recipient: age1sq0wjrxgd2p0kl55cl22306l3lyzt5n0hdmqny6tr9qfkwyxu3aszelc7a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWlYvMVJzekt4SFUwMWUx
        VitCZ1ZXZ2RaQVovMWFZZU9LSi9DYVU5d1FJCkExc3dtTS9KTXVaN3l6Qjd0OE5J
        Slk4a2JPR3MvOGhMbEduTWhKd29HSEkKLS0tIGNnSFY2RnBwTnF4enBEK1lzbGdP
        NGpWUkg3bU9kVWtHMVFIOUJIV2dhZW8KdIaNcH7fKpmqE6f+TL80biCciIqNJOVC
        AO0hrBd+Ex8tVf+OY0lEpHtJagSyTLWA5ScjyXYwzTYswCgf4gWHlw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-05T05:56:50Z"
  mac: ENC[AES256_GCM,data:KJYEJigXSXILQVFUfcjRrCL9RP1sH3AuGl+FBKuo2o4ypMb2RQUawiBafhJoqLgEw1NdOA2sGgr4a2bFdSAUxR3pcLnQO+3s6RdtTUIP+W0jJX3XXKGLFHYFV8y/o+ISNkcm6Aa7ooxVdYuNp7ZiQR5Z9lh1J4x2QRTZJBBnFtM=,iv:cYAAwTzdfgu2VaO+XHbeiKr3wvHRZdjQU4BHm0rs45Q=,tag:jSlh5hGfMXz4/EbD14S7Vw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
