apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  diskSelector:
    match: (disk.transport == 'nvme' || disk.transport == 'virtio') && system_disk
  maxSize: 100GB
  grow: false
