---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: openebs
  driftDetection:
    mode: enabled
  install:
    disableHooks: true # fails with oci
    remediation:
      retries: -1
  upgrade:
    disableHooks: true # fails with oci
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    # Refer to https://github.com/openebs/dynamic-localpv-provisioner/blob/v4.1.4/deploy/helm/charts/values.yaml for complete set of values.
    localpv-provisioner:
      localpv:
        image:
          registry: quay.io/
        basePath: &hostPath "/var/mnt/host-nvme/openebs/local-hostpath/"
      hostpathClass:
        enabled: true
        name: openebs-hostpath
        isDefaultClass: false
        basePath: *hostPath
      helperPod:
        image:
          registry: quay.io/
    # As per https://www.talos.dev/v1.9/kubernetes-guides/configuration/storage/ for talos
    # mayastor:
    #   csi:
    #     node:
    #       initContainers:
    #         enabled: false
    #   etcd:
    #     # -- Kubernetes Cluster Domain
    #     localpvScConfig:
    #       basePath: "/var/local/openebs"
    #   loki-stack:
    #     localpvScConfig:
    #       basePath: "/var/local/openebs"
    #   io_engine:
    #     cpuCount: "1"
    # Just using openebs for the local pv storage for now.
    openebs-crds:
      csi:
        volumeSnapshots:
          enabled: false
          keep: false
    zfs-localpv:
      enabled: false
    lvm-localpv:
      enabled: false
    mayastor:
      enabled: false
    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: false
    loki:
      enabled: false
    alloy:
      enabled: false
    minio:
      enabled: false