---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name lldap
  namespace: &namespace authentication
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  prune: true
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  targetNamespace: *namespace
  components:
    - ../../../../components/volsync
  postBuild:
    substitute:
      APP: *name
      VOLSYNC_CAPACITY: 1Gi
  path: ./kubernetes/apps/authentication/lldap/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  dependsOn:
    - name: envoy-gateway
      namespace: network
    - name: longhorn
      namespace: storage
    - name: volsync
      namespace: storage
---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name lldap-bootstrap
  namespace: &namespace authentication
  annotations:
    kustomize.toolkit.fluxcd.io/skip-cluster-secrets: "true"
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  prune: true
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  targetNamespace: *namespace
  path: ./kubernetes/apps/authentication/lldap/bootstrap
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  dependsOn:
    - name: lldap
      namespace: authentication
  postBuild:
    substituteFrom:
    - name: cluster-secrets
      kind: Secret
      optional: false
    - name: lldap-bootstrap
      kind: Secret
      optional: false