# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
version: 1
metadata:
  name: home-assistant
  labels:
    blueprints.goauthentik.io/instance: home-assistant
entries:
  # OAuth2 / OpenID Connect provider for Home Assistant's openid integration.
  # client_secret is read from the AUTHENTIK_HOME_ASSISTANT_CLIENT_SECRET env
  - model: authentik_providers_oauth2.oauth2provider
    id: home-assistant-provider
    identifiers:
      name: Provider for home-assistant
    attrs:
      name: Provider for home-assistant
      client_type: confidential
      client_id: oQPwXiHu2btpmoybgUq2j98RE4ngoF6s3QmbHxRY
      client_secret: !Env AUTHENTIK_HOME_ASSISTANT_CLIENT_SECRET
      sub_mode: hashed_user_id
      authorization_flow:
        !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
      invalidation_flow:
        !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
      signing_key:
        !Find [authentik_crypto.certificatekeypair, [name, authentik Self-signed Certificate]]
      property_mappings:
        - !Find [authentik_core.propertymapping, [managed, goauthentik.io/providers/oauth2/scope-email]]
        - !Find [authentik_core.propertymapping, [managed, goauthentik.io/providers/oauth2/scope-openid]]
        - !Find [authentik_core.propertymapping, [managed, goauthentik.io/providers/oauth2/scope-profile]]
      redirect_uris:
        - matching_mode: strict
          url: https://hass.${SECRET_DOMAIN}/auth/openid/callback
  - model: authentik_core.application
    identifiers:
      slug: home-assistant
    attrs:
      name: home-assistant
      slug: home-assistant
      group: self-hosted
      provider: !KeyOf home-assistant-provider
