# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
stringData:
  client_id: ENC[AES256_GCM,data:KG8upkDB8uFPxRsmeYn8OYk=,iv:XoqxH5pDhAGKgA11ryk6am6v+V1bN6ykTDd/D+zT58g=,tag:dMNbRDnL8wYctLigAmXRoA==,type:str]
  client_secret: ENC[AES256_GCM,data:63WUmFMPB3Y467JubiGG2b2kSxpFaXN7kWilmH5FX2v1m35eXoAHm+1gRSBb4243dgmYKy+pCsoiiTC5rFX3JQ==,iv:TOR3cxxgN9owIv22vvrGKdisi73/VniOktokeeXfci8=,tag:vTn4Xi2fAUu9wm8xMy7BrQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuNXBJS2Y0RkUxbTdKVElY
        aW52RENxbFlmQ0RGcHlJaUlPVE5QcFZMYlRjCjdBSG9HLzR2WWpMQmVlQ1p6VlhO
        YWNmd2FpZ2g1eVQvRWdNSWFrM2JVSlkKLS0tIGxIRVBBaDJqRVF0bzRrQmpTV2Zt
        NndSeHBFNXR4cUFmNW1jSk0xTStIejAKG+I6UWwQ7ywmTeKP6iXG1xVx/YnCKT5H
        7qu3duEQrbpw0WbcyzWZd2F07bfVh0usnLSxJ6E/wsOQSb6wuwKCIg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sq0wjrxgd2p0kl55cl22306l3lyzt5n0hdmqny6tr9qfkwyxu3aszelc7a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-05T05:37:14Z"
  mac: ENC[AES256_GCM,data:JWBYAACJBkUwXpQt2MCUT3atPYkMrJdqT4GyN99f+kXMWksIouZ6MggJAQhPITjEtaehDE3lPmYWCUWj7fnaeTuE38U5jU87BErsF9TKa49CknUvKedUgGJf7aKsBqihB0duyI9a+yUsNyG3uJjjV/wfgDNjLord++Hov4H9qLI=,iv:ESKO//4h8VjyNIT8SjlxY58pUW8acmW4bCfcJX6p5XA=,tag:2rW7DnS/IipG7xuAc48X/g==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
