---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app lldap
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: lldap
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5
  values:
    controllers:
      lldap:
        pod:
          annotations:
            reloader.stakater.com/auto: "true"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
        containers:
          main:
            image: &image
              repository: ghcr.io/lldap/lldap
              tag: v0.6.2-alpine-rootless
            probes:
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
              liveness:
                enabled: true
              readiness:
                enabled: true
            envFrom: &envFrom
              - secretRef:
                  name: lldap-credentials
            env: &env
              UID: "1000"
              GID: "1000"
    service:
      main:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 192.168.2.250
        controller: *app
        ports:
          http:
            port: 3890
            primary: true
          web:
            protocol: TCP
            port: &port 17170
    route:
      main:
        hostnames: ["lldap.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            port: 443
        rules:
          - backendRefs:
              - name: *app
                port: *port
    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /data