# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin
stringData:
  PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:fyiJj4NAkK0QEpL1VP8=,iv:/e0TfV4p4FOMdaD/zqGFHcg27vTOH490nYBG6OF7TOg=,tag:FxMJJS8sGHUYM7u12XIFYg==,type:str]
  PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:6uDLl/4BE2MZzUEs65u/lPBUmm+lyyjDfutmnA==,iv:+qE1jditEhoVfeqEgQz2fpIfkDzL/n34GXexMpvdNE4=,tag:wy9vFjj0ZLgM5HbFZgfDJg==,type:str]
  config_local.py: ENC[AES256_GCM,data:kh36cn4MJY+LF3BFaikL1X/zsECAflj1c0IfDUxFAyW005sBttsEZYOhbci0Lk7IsKKYpLKeDgQKD48o9Bb21511dK4VZxOR1dSneS2QbtOnXfuQ9109hjLgKWAn2/1u8v3r5lnRuHnNeOcN3k4OSQ==,iv:Bqbq7sUlULyQlKHk2DSjCoY0Ze1hr2UUrNxKMVQkTe4=,tag:vGxibTPLBcidhIjCYp8FHA==,type:str]
  pgpass: ENC[AES256_GCM,data:VZRPMMqSjvRcbAj75GoHKxH0ASeJVAe7/Z6SjnSBGyWcNaXKEKORQGiK1g==,iv:aWO1eRN3alykCL0+wIOoJYqrRoiTHCbS0FtfTxl5GPk=,tag:bnlmgcE7SIduTnsd/lbDhA==,type:str]
  servers.json: ENC[AES256_GCM,data:uo+LqDBF9+78d5KbNqzb46zi2jfA2hqWYJz0iNo5l3EHiNJlabjk8ysG/7uh4PLpIQh3OTC3BLWNXzUmAx/ljoCTYglZ6HGGU/O5/YNhfDcSLrTs73/Le259kTtUzS6bkEOKWlwqrHJP61I5LpPrsVrjoyHpWLZkzokxlGMSstKGch252REsadOV6SLcckxPfC3SQ1fEAikynOVCE3aTw8/ak2ecPHU99osDSRREDBbm041lPdz3vgpvblR/IPbtI7SEfKv1j7vHY7AI398LLq6maMiT4C2RwFbGsl6STzyEw9TmOK6FAh6GEH6D/J+8YwOmCeWpYCTus9KoSAffCmXGiMlSLDuczBGaagU5VGeA/PdKqQWgEFI0SOrenjpObQuur4knC8e5MQ0rtMJ3P6VymOHadYM2j+0O+xtx1y1jw8li+Y1jy6xw/GTWWLFNyCOQDFwTUxN7IshMawzd2B5V5BshVOgGdXzkte8aYmzLTmBiGDkg0j8Pr0WbFhlCR7ogL9uRslqqtsYAsiR784GOMrIHpJRXb+f3ECpO/VIeTmGCQRY+tVLHclfMbK2aIXYOwlYtUglkPugLkamjxZAyIEsqpcjEnIvRRB6/A4HIRPxnFjHyaO8BkmxRG3V+QTXwCRQ/FKPxzsim7HumJOxdcr+js4bl8V76Q5UojNAYHggNYvb4oxCsvoaA3kUONwOmBNxx7Hoogox5McUaGg==,iv:YEzPS8s8quL49I8a8ra0mjuWNrSMZLTmlImGZc0suzg=,tag:KzdFAvHVaanncnLm9XrdiQ==,type:str]
sops:
  age:
    - recipient: age1sq0wjrxgd2p0kl55cl22306l3lyzt5n0hdmqny6tr9qfkwyxu3aszelc7a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQjhQbUZRd2oybW5jVDc2
        WER5VnUxWUhPY1k4ZjV4c05kcjVNZ1VvYncwClFSMWxadXlNU3lQV3ltRk5xMU5S
        Y01ZeFNTcG5BeC9ycWpmWFp3MWZabG8KLS0tIG0xd0ZDOGVuYkQ3VE1xTUdONjNh
        T25EUTJSWjIydkhNNnkwWmlYTk1vdG8K0LOso5hLbqSD9xxhcR8wdK0PbfEV/whA
        w/b/wo4r3+hKEdKEJPGCfxAERG4PRJQGiqhVPh7UxRE/qKXjrH4lgg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-13T08:42:23Z"
  mac: ENC[AES256_GCM,data:Zl/OOp2WZbx7elk8RtLH9eStJzS5GJSMaiB+LIbI8h+e4O+1AqwOidy5UjHra19taFEBwnUJH61ImD+LMufiv3WLhK5qBc5tubyToDusnq6M8Gt3hswEoTfU4Pgq7E2nTEaiUclsv2BYq8nWyfz7Lk0SVUlmM2TycTW5x+pA87w=,iv:zj7ZYD5fv49ojQcu2h9SEjD4WjLTvqLgkFkll2z9Bwo=,tag:qbkt/Hta0sR/PmIUcKvqrQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
