---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentication
components:
  - ../../components/common
resources:
  # pull this secret in early so that it is available for postbuild replacements
  - ./lldap/resources/secret.sops.yaml
  - ./authentik/ks.yaml
  - ./lldap/ks.yaml