---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../components/common
  - ../../components/repos/cluster-template
resources:
  - ./kube-prometheus-stack/ks.yaml
  - ./grafana/ks.yaml
patches:
  # privileged on namespace for Intel GPU device plugin
  - patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: system
        labels:
          pod-security.kubernetes.io/enforce: "privileged"
          pod-security.kubernetes.io/audit: "privileged"
          pod-security.kubernetes.io/warn: "privileged"
    target:
      kind: Namespace