# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: volsync-maintenance-secret
type: null
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:DfhFKUqBfUe/EJLY00sjjZrMRd7nUphT,iv:s/degv0cWIJP53dEh9m7DsUMFgdxn95XJREpPeJ97RI=,tag:C3qRsj5QqkzLq39LqVEolA==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:W7PFMdHI/pDFBpFSHlWvig9Cn/BefLqZnfriBg==,iv:BkhHMhd7DxgXWYFpqayJRLw0zuWd01T6fjxRM0Jd5Dk=,tag:0z/5TnrkswMAzp8pJiJjbw==,type:str]
  KOPIA_LOG_LEVEL: ENC[AES256_GCM,data:vsBYR1k=,iv:fs7neqXsedTN5aoW8aZrB5Z7UZnkxCuxxJysfc8uwCs=,tag:GkzShoipdGD3DjkqM7TFuw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESXUwK3lqWFJ4Zk5RMGJZ
        VmxzYy9WZUFWZmJaZzVkTFU4cHFZeXhvaTJFCllPaGlhUWphVzMxRFQySFk3amtH
        YjlxNExsRzAxbkxOSzV3cW5jbDJlZ2MKLS0tIGNwdmlWb0svZjhyanJWaXNhdFA0
        V0l6UEpKSlpqZEdlVEpSZ1BiZ3lwWHcKpxh1bxVyTlK0vdRRTKGzJnC7D0pBd1IR
        UtxFbd21aAt6VhplO+OERX39pPVtJtIhpyoXR2/0rTqB5mjYHizrSQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sq0wjrxgd2p0kl55cl22306l3lyzt5n0hdmqny6tr9qfkwyxu3aszelc7a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-22T20:02:46Z"
  mac: ENC[AES256_GCM,data:EMaLkOgtRiOJFituWOJ4i7bmhPUSblBJAdJ5SalShYCTxGc9I6D4T0f11/0Af/8v3iXI9vpg1EClBDiKie9YO4gCft0VkCm4qLerZtFS5NOG86RMBWmSQcAQN/z0XQI8xNsNpBHMtTA/ViWZWfzUPldr+4ZOSFfbjjLSN3wh6JA=,iv:PArsx5pOEnDq+chvFDgInm8BjAg2hj5G16mJulQyyRc=,tag:CIeckBvUv2e0sGezE3Zv2A==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
