---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app palworld
  namespace: &namespace self-hosted
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: longhorn
      namespace: storage
  path: ./kubernetes/apps/self-hosted/palworld/app
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 100Gi
      VOLSYNC_STORAGECLASS: longhorn-ultra-fast
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
