---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ocirepository.yaml
  - ./helmrelease.yaml
  - ./certificate.yaml
  - ./referencegrant.yaml
configMapGenerator:
  - name: authentik-blueprints
    files:
      - ./resources/code-server.yaml
      - ./resources/bazarr.yaml
      - ./resources/prowlarr.yaml
      - ./resources/radarr.yaml
      - ./resources/sonarr.yaml
      - ./resources/tautulli.yaml
      - ./resources/homepage.yaml
      - ./resources/grafana.yaml
      - ./resources/home-assistant.yaml
      - ./resources/immich.yaml
      - ./resources/ldap.yaml
      - ./resources/embedded-outpost.yaml
generatorOptions:
  disableNameSuffixHash: true