# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-cnpg-secret
  labels:
    cnpg.io/reload: "true"
stringData:
  username: ENC[AES256_GCM,data:hpxxezOLMGQ=,iv:DH/ngFtLetTp54aqMfVxwhf/nJVIGwXdk1ovygw2jQo=,tag:MFKMY1Mh5ZqJMlD/HQmjNg==,type:str]
  password: ENC[AES256_GCM,data:zZ07v5EazKzkz7aGBa0QZKxEoHjXkfV7eZKy9A==,iv:hKnu4p00giJXMEoLM6lsT3vJ5w2yHnRzhFFFq4rByQo=,tag:lmrWH0rMD7GKosnQ3joCDg==,type:str]
  BB_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:SZ82JtFNEi7JaYldqhGIyft1P6GLBy61rR/j8q/QKQ==,iv:fdzLZ9l4uyEzd9tA/gDCcLi1hGFDboooAHMSxSKrIdw=,tag:wviQ1B0KbbO9aEag1cj2iQ==,type:str]
  BB_ACCESS_KEY_ID: ENC[AES256_GCM,data:8VVPVU2LSuZ0Tk2K/D37s7wwylBaRaEwbw==,iv:oZRQ2fNI8zn/ZAeCfu1JYTLjyKqU//IYmVAe9CarBhw=,tag:VpE0tECf88mWOiqJvM/+EQ==,type:str]
sops:
  age:
    - recipient: age1sq0wjrxgd2p0kl55cl22306l3lyzt5n0hdmqny6tr9qfkwyxu3aszelc7a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZ3JCK2puTU8xRlk4Qmxw
        Z2ZNZG1FaVMrZUlzODFqcWZhZkRaNzZWUmdjCmpqa1lldGlQcFZqQjhLQXVIbTd2
        aGF3N09ZTGNtZ2NjdWxpTW0yVEtiT2cKLS0tIG95ZThhRHh0QkY5dXNuTWpRYjJo
        OTFac2pGNkpZZW5maWs4VEhrVjRPTlEKL0NjP1UejjV10Vl0z4IIdpqUumyndiPo
        iCvD96BAkMfjXOHWOotrnlR7v9t5t3uGcxCvBrp0pJiONhZ3e5py+w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-13T04:08:44Z"
  mac: ENC[AES256_GCM,data:MpmZYQQZOEm2NtCEMVKXmYHhDAfkKSmN1ng7bve9ouhjSIHapg+3bbqUsEP/3dBl6o1hYuwAR3a78OHqfffD0JNPXy0kzcxMhDlbBD7dIBQQuZR8TES8oBvzBuSTUHYmOeOJulYEOkgLhaKSK6UA37ZqXBTVhztuC0aeSN4vc8o=,iv:gYlHOWNqodxKzuYHm7ZFKUdkq4VpDRYGIy7R6RwRVug=,tag:ToQKhg0BmlLpoB8durRUZg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
