---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./ocirepository.yaml
- ./helmrelease.yaml
- ./httproute.yaml
- ./storageclass-fast.yaml
- ./storageclass-single.yaml
- ./storageclass-single-ssd.yaml
- ./storageclass-ultra-fast.yaml