kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-single-ssd
provisioner: driver.longhorn.io
allowVolumeExpansion: true
retentionPolicy: Retain
parameters:
  numberOfReplicas: "1"
  diskSelector: "fast"
  dataLocality: "strict-local"