# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: palworld-secret
stringData:
  #ENC[AES256_GCM,data:AGyDmnrWIbmfbnNB8fw3ZbAVfLlPG15Yra8YayHM2k9H5HDsrZtVugi2YaPdO08=,iv:oGb8zM/yQCmr0104xnC+UolA8uoDRI5zdqR28esp7xo=,tag:6/W2XFCcxOQSVcpUMOwkfQ==,type:comment]
  SERVER_PASSWORD: ENC[AES256_GCM,data:GQ==,iv:pYxdeMd1IJYBoLIMQNIhjMeluWEvr8PvUdPDOzhGQts=,tag:SZc0WouH1/hGqfdRpVL1jg==,type:str]
  #ENC[AES256_GCM,data:pOppyoQ/IwFsP9QVOs/t+wI4cYXDc+9vCOkcSWo=,iv:IUXoqZTAvducNHPWOGtDgMDHj1/po32oka/UtPUzcZk=,tag:ktUoqg3hO12Cw3H90pDZjw==,type:comment]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:qCvB85Z1PmKXSTe/IM13hCyMudg=,iv:LSLZsme6jl3vyvN5WhN6LaX2jqF4C8Fxwj82gETfFuc=,tag:G8Ki3IyV6WFjyeSvcdIgsQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcUNGZEU2YjVRUlZUaVZt
        Wk00TE1xK0J2eXhPL25nQmVBeXBFY0F4WHlnCm00bExmOXRHaGoxcGwvT0ZFMEVn
        emxkbDhxL2UvSS9oUGZ4eFJJdDNDNjQKLS0tIEtYeG80VTBWQWFBMy9kL1ljcmd3
        ZnpPOHpqZGloaWloVEFBLzFaR3ltT0kK0w2zN465/Ln34jIyv8hEzV2COg8bGXle
        arAo8gvLaMNu7aKPOXSC7L6rjvg8vtVMuqlEKJVCTvXzgaz/2QR76w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sq0wjrxgd2p0kl55cl22306l3lyzt5n0hdmqny6tr9qfkwyxu3aszelc7a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-17T04:23:38Z"
  mac: ENC[AES256_GCM,data:MTA9ovuEiHo6xAlaLO8xSimd9s8qpviKVH4QNrrK2XRXosoRHNkQmbFnLHLSFck4bOT4j1UMlwY2nVIeGUa8qlwvkucJ43M7YIy8j0s81goM8LPRiP8drOG5FcQg252n7bTe1py2YaMcjc+fkwaElu+4XbXbY1BgKdHwtnkQ/ek=,iv:yHEkI1NRSKQAEt6nCcjs0ALdoN00wOg1sHDr2HbmIoI=,tag:Cd0JD97sMBSSuPhvw+R8ow==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
