apiVersion: v1
kind: Service
metadata:
  name: cdi-uploadproxy-loadbalancer
  labels:
    cdi.kubevirt.io: "cdi-uploadproxy"
  annotations:
    lbipam.cilium.io/ips: "${IP_SVC_CDI_UPLOADPROXY}, ${IP6_SVC_CDI_UPLOADPROXY}"
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 8443
      nodePort: 31001
      protocol: TCP
  selector:
    cdi.kubevirt.io: cdi-uploadproxy