apiVersion: v1
kind: Service
metadata:
  name: cdi-uploadproxy-loadbalancer
  labels:
    cdi.kubevirt.io: "cdi-uploadproxy"
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 8443
      nodePort: 31001
      protocol: TCP
  selector:
    cdi.kubevirt.io: cdi-uploadproxy