apiVersion: v1
kind: Service
metadata:
  labels:
    lbipam.cilium.io/ips: 192.168.2.204
    kubevirt.io/vm: ubuntu-dev
  name: ubuntu-dev
spec:
  ipFamilyPolicy: PreferDualStack
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  - name: httpd
    port: 80
    protocol: TCP
    targetPort: 80
  - name: vnc
    port: 5900
    protocol: TCP
    targetPort: 5900
  selector:
    kubevirt.io/vm: ubuntu-dev
  type: LoadBalancer