apiVersion: v1
kind: Service
metadata:
  labels:
    lbipam.cilium.io/ips: 192.168.2.204
    kubevirt.io/vm: ubuntu-dev
  name: ubuntu-dev
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ubuntu-dev.${SECRET_DOMAIN}
spec:
  ipFamilyPolicy: PreferDualStack
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  - name: httpd
    port: 80
    protocol: TCP
    targetPort: 80
  - name: vnc
    port: 5900
    protocol: TCP
    targetPort: 5900
  - name: rdp
    port: 3389
    protocol: TCP
    targetPort: 3389
  selector:
    kubevirt.io/vm: ubuntu-dev
  type: LoadBalancer