---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu-dev
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      labels:
        kubevirt.io/vm: ubuntu-dev
      annotations:
        kubevirt.io/allow-pod-bridge-network-live-migration: "true"
        k8s.v1.cni.cncf.io/networks: |
          [
            {
              "name": "home-network",
              "namespace": "virtualization",
              "ips": ["192.168.3.10/16", "fd00:192:168:3::10/48"],
              "gateway": "192.168.11.1"
            },
            {
              "name": "cluster-network",
              "namespace": "virtualization",
              "ips": ["10.42.100.10/16", "fd00:10:42::100/56"]
            }
          ]
    spec:
      evictionStrategy: LiveMigrateIfPossible
      domain:
        cpu:
          cores: 4
        resources:
          requests:
            memory: 8G
        devices:
          disks:
            - name: ubuntu-dev
              disk:
                bus: virtio
            # - name: ubuntu-os
            #   disk:
            #     bus: virtio
          interfaces:
          - name: default
            bridge: {}
          - name: home-network
            bridge: {}
          - name: cluster-network
            bridge: {}
      accessCredentials:
        - userPassword:
            source:
              secret:
                secretName: ubuntu-dev-credentials
            propagationMethod:
              qemuGuestAgent: {}
        - sshPublicKey:
            source:
              secret:
                secretName: ubuntu-dev-ssh
            propagationMethod:
              qemuGuestAgent:
                users:
                  - nospamas
      networks:
        - name: default
          pod: {}
        - name: home-network
          multus:
            networkName: home-network
        - name: cluster-network
          multus:
            networkName: cluster-network
      volumes:
        - name: ubuntu-dev
          persistentVolumeClaim:
            claimName: ubuntu-dev
        # - name: ubuntu-os
        #   dataVolume:
        #     name: ubuntu-24-04-desktop