---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app code-server
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  driftDetection:
    mode: enabled
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    controllers:
      code-server:
        type: statefulset
        containers:
          app:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.128.0@sha256:bd4a3a022ff016954bf9ae6ea0bce6c7eef96a69da4d2fe34552638f32d4820c
            env:
              TZ: ${CLUSTER_TIMEZONE}
            args:
              - --auth
              - none
              - --port
              - "8080"
              - /home/coder
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop: ["ALL"]
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 2Gi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true

    service:
      app:
        ports:
          http:
            port: 8080

    route:
      app:
        hostnames:
          - "code.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: http
            timeouts:
              request: 0s
              backendRequest: 0s

    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /home/coder
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
