apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  #ENC[AES256_GCM,data:ESVsjbigfzNGp+8AVH//,iv:8kKycezRb48U7UfNn1FJOroc3MrgfDg/bTRL94sXmN8=,tag:HY9VCC8JLGaRL2gTzfJm0w==,type:comment]
  SECRET_DOMAIN: ENC[AES256_GCM,data:uAv4HeJM,iv:jRKPTw6ucwc3P6UFbIp6k9fX8FG95CC+MEbDKuqccWw=,tag:0Ftf4Jw27TlA8Txwgq79Gw==,type:str]
  BB_URL: ENC[AES256_GCM,data:Y4AEj1p/BUgbSSaJ/Yyl5lV2HNgHsbsnTNV3xlhw4s4f6IMM4g4=,iv:zUmfhAmiql/9jAF5Uh8Fj4K4SRb1XGAOA/bCOMTK2ys=,tag:6b3fkRFnZxhG+eVl848WsQ==,type:str]
  BB_BUCKET: ENC[AES256_GCM,data:grKgTQR3FD1V3QFokYPlK54=,iv:dFqEjYg0K4f5608Vuh1ZsSRjQhBZkkKHT9EJa7GoUNY=,tag:wwVnkCJo1zRLkJJexKwUxA==,type:str]
  #ENC[AES256_GCM,data:9DBvgMP/XhxlKYAJdRvBfg==,iv:F3Yqrro9hvpEMpsNieAXw//k6ujt73d5bjJUZJbZQhg=,tag:8eqgtsw6C9sidLDBdg7hYQ==,type:comment]
  CLUSTER_TIMEZONE: ENC[AES256_GCM,data:XCq77HtonR2P7wu2YrEPTBzrbw==,iv:yH0jG/9fcFy+82Yco7Bq4dRJn+baMkyanLXO6by0Qng=,tag:Lul3/8XwFcbGoQ60m+cHog==,type:str]
  #ENC[AES256_GCM,data:LPzkahtYd/6UAC4F,iv:SlQcVaQi4s5RKGCfus47QfSFn2j9uG1eUfuVrkB9nZw=,tag:SlCPRmKQ38ebU5Z3koZa3A==,type:comment]
  IP_GATEWAY: ENC[AES256_GCM,data:q2U1zwPxWcyUOUjM,iv:kbbevkdDM71Fi0xtSp+oPKn7dEGMdsfZ25OW1XmIhMg=,tag:2PYaSn0YL0xwAAz+N7KziQ==,type:str]
  IP6_GATEWAY: ENC[AES256_GCM,data:4QkzpwBPekQr4hzyuRuBTVBZ2xUBkBMo,iv:1T/XwFfph+BdbPZMKV/3Ammk+hN0WQGweac7DrQhE3g=,tag:HtSu6pSP/9nCFKv+KUk35Q==,type:str]
  #ENC[AES256_GCM,data:Qz7gaF9MHrKidZVj1qrPmCfQWqCO,iv:Dg67DqMa2C7HfD9uoE1rVohDTRXNj5S+FYzww2G6i2U=,tag:l1fGCgaBzxe7lQl7GT/ohg==,type:comment]
  IP_SVC_HOME_ASSISTANT_CODE: ENC[AES256_GCM,data:a5QDY7HtSF0M3MTp+w==,iv:HFROSI8UBFbDQFIEXhRH+SyrFog97JN9/PZEQRv+VTI=,tag:pKusBl9mBsFyvyj2uW2iyA==,type:str]
  IP6_SVC_HOME_ASSISTANT_CODE: ENC[AES256_GCM,data:K86OYH2axVWryznSpXDRcTVDsw==,iv:0+541AreEa7lFak5E3FX58GDKqhVbIoeFYNg6wro5jA=,tag:cdV/syt2HMbv1/Ygb6mJNg==,type:str]
  IP_SVC_HOME_ASSISTANT: ENC[AES256_GCM,data:ZzMCmYSDQS9iwF+Ylw==,iv:vpWJ6L4q2C5qwQLSu2NlRnCa1y8ItKOxnulxjKOuIzM=,tag:DalLNCXhe4HZUWpEINJoPg==,type:str]
  IP6_SVC_HOME_ASSISTANT: ENC[AES256_GCM,data:B0VSWuAATpGM/b2vYAYM1Q66XQ==,iv:ksXdX8jDPqDRa9y5OkVOCWCaKwWnM52i5u/k8YHIIR8=,tag:6WJNER8YChqD4+38HP7odw==,type:str]
  #ENC[AES256_GCM,data:TVkVv1yFh7Kp+GvwsDVn,iv:p2d6bKEGLDE45FOMr63uxz8eY0xVAsKszA1nqylemMk=,tag:aRhbUVoQYbTCaPxKnAVjSQ==,type:comment]
  IP_SVC_PLEX: ENC[AES256_GCM,data:yZ2rGTWrOUwo1lomyQ==,iv:zxQIJLw7Sko8G/zi4xJkBpKRJGA2fw6BGifKCGed4fg=,tag:8jvgIPAY9zF69aUc59kygQ==,type:str]
  IP6_SVC_PLEX: ENC[AES256_GCM,data:Nl33j8k0lMF+/DSj1VoUXlEMcw==,iv:blYhubC+syF5NJpHeHCNqJOq4tr66MrFfdH7U0D7SEw=,tag:bRUUG3eNcspU1EvsdbkKfw==,type:str]
  IP_SVC_QBITTORRENT: ENC[AES256_GCM,data:BhJBXcgRlS3OkCaZJA==,iv:P4SvXPdQGN7Uu1+wa1MYCZZRPzQ81Z2kdR8expAi4IU=,tag:KrdvVEFBabhJ6snSjtQ7pw==,type:str]
  IP6_SVC_QBITTORRENT: ENC[AES256_GCM,data:i0zO+Eb+y6CMBX+t542W8JuqcQ==,iv:FTHgEWqziPZqwwoijto3PjMzr37IJXp5koMN8vJ4uLY=,tag:Gbu8Dcl6bCtO5B7VFaeaFA==,type:str]
  #ENC[AES256_GCM,data:Cu3M7SmpzGUMvwJKTZU=,iv:J2tY2HG2Xt0G9mRbSBnl2blsQKHlUtksnnZIoKI2LIs=,tag:+LSehuYIrFH419oWfcNstQ==,type:comment]
  IP_SVC_ENVOY_EXTERNAL: ENC[AES256_GCM,data:eWRIo5SxedI5ecndOQ==,iv:CwZvpl32YslrmFI3geuV48PRowBbNFekQnuUfVVYnO4=,tag:MRlOVHsj8mnKi1yZqh0L1w==,type:str]
  IP6_SVC_ENVOY_EXTERNAL: ENC[AES256_GCM,data:ZFz1aoKhNLxAf/yizihAwfzKRw==,iv:/Ecy0e/iUJVJvSklawm7nMMgijfziugeOlOpOUoDqS4=,tag:PTSUFMbfTccTyXwPN+sR8Q==,type:str]
  IP_SVC_ENVOY_INTERNAL: ENC[AES256_GCM,data:jy29O/jL5YrR3pwfSA==,iv:A2sL+e5HkGIoWTgs6+JsDLtnafbZ4nLUd64VU0Y9ckY=,tag:EE4DnZzFHf+gyLv1FRA78w==,type:str]
  IP6_SVC_ENVOY_INTERNAL: ENC[AES256_GCM,data:HaKFz06WsWucHvqcNgi6q3PvbA==,iv:cfyzg1RnBalsRvrx4UVZ88nZH8j+mdBCodl10wkPics=,tag:yKO8CTaK/tpb3o2kWZfE+g==,type:str]
  IP_SVC_DNSCRYPT: ENC[AES256_GCM,data:2eomx9uA3hgcEkSPyA==,iv:bcX7fEOHxrk9o5QDkjyrMISXgu4lyzFXNVBy4y2Sn/Q=,tag:WqHnSw9TDulEJ2CuuwucNg==,type:str]
  IP6_SVC_DNSCRYPT: ENC[AES256_GCM,data:07yAiywopYpWJ7E7PMc8yytKrw==,iv:tHHJL4yre0UR001RYoPpr+HrsVmHcKD2GvC0QF9YQYw=,tag:tGaKIUmAxjIOHEiZN3bC8g==,type:str]
  IP_DNS_PRIMARY: ENC[AES256_GCM,data:sGgkFbdmCvduq9E+Nw==,iv:djxzCDu/CVnQb8i0KU2u253VK3o5Q89V0wDNS6MVH+0=,tag:SpAxnDZgPZbw5HHIok7o1g==,type:str]
  IP6_DNS_PRIMARY: ENC[AES256_GCM,data:chrYGjYPFViCTooqKWPXWDSF+g==,iv:TuUN3/SdXzStjdfOXBcMjAfYbxVN8Jw3fosEvcJJgRw=,tag:fzIeQLbHk/JDzK8sdNbm0w==,type:str]
  IP_DNS_SECONDARY: ENC[AES256_GCM,data:bsvSYEL8oaHReBs+,iv:+X5XlbvlIN5OCiOeRNN3G3LJ7Fdy+gFpXCcwbetWLAI=,tag:IM6nK7C1JK4vwiIunxArdQ==,type:str]
  IP6_DNS_SECONDARY: ENC[AES256_GCM,data:Q852psfm7w5s3jasV5MUX9RZ,iv:8Ft5m/b8F4zEbGijVcRE8InKJefPu4O76PqsZjQRGNc=,tag:OGmedQPWABTZD+iojGjtYQ==,type:str]
  #ENC[AES256_GCM,data:1RH/TM3SkZba6iXxIgeCXw==,iv:UHXd47WVAPQiIi+yWeV9QIcsRzNz3IzI3VA7gVW/oos=,tag:msRVa+xvM8eNgw8x0r7RLw==,type:comment]
  #ENC[AES256_GCM,data:j2a+SQ==,iv:Kl6X6x5ANcg4dzdE4GUPedAsWtlR75hTVNuXtyOqQU8=,tag:f8e6EpsUWE1zqTqR1R9e9A==,type:comment]
  IP_IOT_HOME_ASSISTANT: ENC[AES256_GCM,data:5jB/qtWzEyA0e9vDBQ==,iv:SOxNGGVnD4DVF684G2QTnL59o/iPajjsp9Dou/qKbJk=,tag:VrgLhNgpICOnZfoeBgjjiQ==,type:str]
  IP6_IOT_HOME_ASSISTANT: ENC[AES256_GCM,data:80nHxpiVV3GQb+WYG6/SU6ALnA==,iv:x1XGbGbi8VcFTY9XuBXuvxGeVf6BcqG5Dipe3HpcUHs=,tag:AgIJGsWeXvzGnzsUJQmR0g==,type:str]
sops:
  age:
    - recipient: age1sq0wjrxgd2p0kl55cl22306l3lyzt5n0hdmqny6tr9qfkwyxu3aszelc7a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRamdhTVlBaHhuMzZ6c2ZW
        Qnh6eWFNK0psVmFkTG9tc05PTGM4bVlGRUFRCktRZzE5MjRVUnJ4bzd4ZXpQckF3
        dFZMRlJXaWZOOXVCTkFQTlVQbFNTSHcKLS0tIFRkOEhWRVJzSkJXbjVNWHNFcndG
        Tm9UVjd5TUpnaURPbFM5YWpvMERnM00KNEZKlrCLp3wR2uVhjb0Xk9FvmnCyXf/A
        qlnG9DyFL6YMJ8bqgSARroKN1wgn8+s7hKaAJ02t3nO0KRjLorcK4A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T04:03:45Z"
  mac: ENC[AES256_GCM,data:Y5HY4Ps47SAhgfWhWJNqKKrcT0cwTAlKB0CHrre91rCtM3yZ3oz7/fMrIwUgOCJhPNiumD6Wm1lfgrf2hIwRUoDV8vpq5wVoOK8mrjA0KOsmxxUt30FvGIl9OOV5CxghINsP1sCzMFN+TFAZAODPEmM6UseY1N3uDljo6YQekD0=,iv:5QXosdfFVSoB7Oj7NOn6iomU/JnsD3Kha0g33WZhlO4=,tag:Os5KIgsxjiJJyWl+JMa2tw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
