apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  #ENC[AES256_GCM,data:i5vcEdW73LDktf/D95kG,iv:bPjy+TO/di6HvIvw15LFqWYLlRjXufqFINJQdOnftjU=,tag:v8y6t2LJZUqpeqqdMCgjFg==,type:comment]
  SECRET_DOMAIN: ENC[AES256_GCM,data:jBM25V3K,iv:Jy8CMmtGAYM2CW/PrWTfMCIpu4opASsgrG9NXWXGYAc=,tag:oGyfFlJ00ffgkMpql4a21Q==,type:str]
  BB_URL: ENC[AES256_GCM,data:ztOINfzJtNNRP70kfpfKPH7n7GsugIp2ReV9o9ZkyU7VNuXVLvg=,iv:/mV8ERy71/kjy4WWjA4NdWoC2H2ViAAaK+91ntd1YTY=,tag:9edLcjXIYL7xgOGrpG7JJA==,type:str]
  BB_BUCKET: ENC[AES256_GCM,data:SMV7MlCy0FPA0uGgQSW/pbk=,iv:0Fgz2W0Fnz6YHX91eC4IiNuwJiW6r9chpKR7seE3G1w=,tag:aX6uJnEaLRHU2nz3tQ9+lQ==,type:str]
  #ENC[AES256_GCM,data:v0A2E3DtWN737Qk3uh5YRg==,iv:OGbYQJuaTR+Vh1T7rewV7SAn5wloTU0/LnRZvyarXn4=,tag:BJFLuBKNb/B8uf2/GZNtIg==,type:comment]
  CLUSTER_TIMEZONE: ENC[AES256_GCM,data:GWwUVU9mwHgLLPSn5HBs2Yo=,iv:4/1/uJ9UNN/K9o3H2keVNmW1VzDTA5ty5EQ5QpTNt78=,tag:HKMjON1Oo5vQhhsXsAu5gA==,type:str]
  #ENC[AES256_GCM,data:ohWo0GanjihakyCY,iv:F54K4kxSEsWnbmTntzoAX21Kn3Fh5XHpcIP1rBpMJNU=,tag:1dGMR7/vgEU34TPd8/hOww==,type:comment]
  IP_GATEWAY: ENC[AES256_GCM,data:x7JK3jT2GxiPi1At,iv:LFRCisAVocM8RC6U32m+LyaU52RQO1w8X6H2IwYuK/Y=,tag:sMe1AFL4KSbpa+foXECnHg==,type:str]
  IP6_GATEWAY: ENC[AES256_GCM,data:vfEPsMkKpNipz3nS/Z8lFTOplVEuTpOs,iv:9RzPh6GjMZQaRYOzH5vTnolo2Sb4FjmS0RLqQHm3/VY=,tag:TYFNyVnNjAkH+7ql37k/Ag==,type:str]
  #ENC[AES256_GCM,data:Dw4HygqafJMA+W+36IdG,iv:mzh6eTiSpM+Sb1VuwHjSY/p8k8vuW9VlTEyVrAWZpu0=,tag:19Ts2x5p/Xx7+PaxpqrDNg==,type:comment]
  IP_SVC_PLEX: ENC[AES256_GCM,data:q394+Ax/51RHLv/OOg==,iv:TetwOziuyWL7IQtiYuGbXcqXC5IwtLhTgwh2NHc25t0=,tag:Ng3AMyOSM9MLKjY3bS6h2g==,type:str]
  IP6_SVC_PLEX: ENC[AES256_GCM,data:skZ57k5qtY9GdpHaN7dkOV3nAg==,iv:XjoeINhMbtA/kCB5P4ipA/nMwceBcf0ky8oX23/rYBA=,tag:AX/pvcdbyLx3Vy5/zRHFAw==,type:str]
  IP_SVC_QBITTORRENT: ENC[AES256_GCM,data:pXZN4hqJIP6gI08nww==,iv:iIOWvF3SDIIOrkOngSNCz825AEX3QD3dELLGy/+U1G0=,tag:6y4qi/GLOExK7tDqrvT8ww==,type:str]
  IP6_SVC_QBITTORRENT: ENC[AES256_GCM,data:WyWHLP8q3HRsQ4Zqk8q3MBJsrA==,iv:xcOww5e2+OMMnMIwPwCrvNArM1wm5vcICGsbGmMQzqc=,tag:aU2C1J9BM72JnADMaiwM8g==,type:str]
  #ENC[AES256_GCM,data:6t38I401yEaLCKC9Rcw=,iv:sdOgMKVbrwzCuXDw2mDmNridTpTenWwHy1V9mKccvSk=,tag:hIjkFrc0qD8LfQK/tpnXvQ==,type:comment]
  IP_SVC_ENVOY_EXTERNAL: ENC[AES256_GCM,data:vbj6rBGujXCvMHYU6A==,iv:w8sdyr5CwSfLsgajW3SDx0+ylg53wMhqiU82uXFSkm8=,tag:GsKnNKAAWI3vBRxtxfRfuw==,type:str]
  IP6_SVC_ENVOY_EXTERNAL: ENC[AES256_GCM,data:H40rDfz/BGymmixMgFY3YWHa2g==,iv:m064cUYe+hyOqAVkmJZCHMfCdIcCSzCoe9TtB1zxH4s=,tag:I7SwVv+64Tr0ReNWNIEXww==,type:str]
  IP_SVC_ENVOY_INTERNAL: ENC[AES256_GCM,data:AMVzrOHQllWdWXimlA==,iv:bewcJMCoP4njH7hq/nBuVglH1itStIJxyZaAXKrWG5w=,tag:cAQGYJVzSoStrQJyXwnX5g==,type:str]
  IP6_SVC_ENVOY_INTERNAL: ENC[AES256_GCM,data:6UHc0PchiT3M3H/h6VuLiaLwbw==,iv:eF7GrubVjtJWr2EsiaVjZo/nieenVl5CG5muUUGhIqY=,tag:E/OFBjJdihtoR5I2ab+w7Q==,type:str]
  IP_SVC_DNSCRYPT: ENC[AES256_GCM,data:b5g9dPOkQEZJBwHILw==,iv:ojmf7qD0QGUxk3FBr7GBk+K9nhJUPvYWNBvFoN/FJUA=,tag:gk9X04ESSHC+gZW06aI1PA==,type:str]
  IP6_SVC_DNSCRYPT: ENC[AES256_GCM,data:/RhMWHL5E7+SLnTubkW086ETtQ==,iv:2/b/G+iMmjFgDMYSyPw+pLSj2JaQhNIKN2AHpGal2Zg=,tag:MEf35tbJJ1TaXmBrQ2SQiQ==,type:str]
  IP_DNS_PRIMARY: ENC[AES256_GCM,data:MGJU1V+Kw1d8yjbNRw==,iv:Sv1o9kjl9B3eXJ1K7rq4P8vLlqzPJhoXuRMPgHCty4c=,tag:Pj6DH9BeYAV53aEgFa/ckg==,type:str]
  IP6_DNS_PRIMARY: ENC[AES256_GCM,data:DlVsT4DKlYvjbqzjiVcorASTPw==,iv:dwo6QGfx8Ov2PeVl0dDVOvBixZMUAm7I2eilKwMdYpc=,tag:k8lltsc8VuSS8vKwZWhNAw==,type:str]
  IP_DNS_SECONDARY: ENC[AES256_GCM,data:F0bWNP8cm0mB9pob,iv:LSJarkFBeT72g5WeM6vkU8QsPOoLI0Q4WLpKk9RmUBc=,tag:e/Y2YyrgFIKJMTeQ7i/0Nw==,type:str]
  IP6_DNS_SECONDARY: ENC[AES256_GCM,data:rij+9hlsMzlOF9PkU3e0HWL8,iv:+4DuEtySUsda19bZt6zUOXRMHCfzFd5pFywGrz0H7Ls=,tag:yx1Z9do2Hy/YWN9ghgw41g==,type:str]
sops:
  age:
    - recipient: age1sq0wjrxgd2p0kl55cl22306l3lyzt5n0hdmqny6tr9qfkwyxu3aszelc7a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZWlqQk8zdDh6VUVCcEdZ
        TGZEUFFzaWp5NDVleG01c2ZEZnpKUTJtenhnCnZlYXVabFNoSkgvbGxNWVBSNzBB
        UmFCU1dQWmZ6ajA5ZjJIRDd6ZzJBK0EKLS0tIElzWnZ1Wi9IUVpiMEdYNlJDR3hu
        N0hyYW00Z0d4NFIrd1pGTmdlbFc0NkUK/BEcPPe6RQi9FfbNIIQNmX2ptrNhaWyh
        6vFFrg0127eK4vlL4dDVXaIahYvXOsvBUW3AJweVAovJlRgNTLiqpg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T03:18:36Z"
  mac: ENC[AES256_GCM,data:rXnk/HfZh+hYaofz1Sqq/3quuNBwfpQ2f2zHUOcpV5KGSNTlGk0jqbdgTwmM2rxHw7y9giHFREneDJp0/w+vhCtsKqHtizRuxiC9RIdR2f1xAqPyG/pZt61I3nMsTo4JFxP5UjnxWO7z4PeCvXQCjQizNZJW7Z6EaxvNGQ5A1aA=,iv:s4b7FycP7t+vSl9UIgb7XoCDuxGw5S9Q3Z0Y1ysAKhE=,tag:hdW+hJWwUPmGf1KPfwKGAQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
