apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./secret.sops.yaml
- ./ocirepository.yaml
- ./helmrelease.yaml
configMapGenerator:
  - name: pihole-configmap
    files:
      - update.sh=./resources/update.sh
      - 02-custom.conf=./resources/02-custom.conf
      - 03-hosts.conf=./resources/03-hosts.conf
generatorOptions:
  disableNameSuffixHash: true