---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: pihole-admin
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:AdYTDBNyH3noJ2DUHztl/Utkf0AuYrNKmJ7pww2G,iv:MWbVoRNH+8/KwvBtUwQoHjL85MpR/H3U/RglELacQQI=,tag:6qK/iDBJ5wjUVojLTJH1kQ==,type:str]
sops:
  age:
    - recipient: age1sq0wjrxgd2p0kl55cl22306l3lyzt5n0hdmqny6tr9qfkwyxu3aszelc7a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MFF2RTZMbW5pY3k2SUg0
        cTdVQnpZY0Nyem9VeVB3cXpzT2dWQlpEVWpRClM1V293N3VlOFR5bTg4alRpRXBX
        VXBqSDliTURORHY0UlovQlFXT0h6SlUKLS0tIGlLQnVNL1NpTFRGNjI3Y014TW4y
        NjFvcS9yUUNWRExVZ3UxSG5DdmZacHMKTv0c5JgEmpqbcCz95bThVUCCtxVn+rhU
        AyyXhZF67jVea0nK43o/3gLKw9Hikiv1O7zHSbMrrNKNrMvY3300qQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-22T21:49:29Z"
  mac: ENC[AES256_GCM,data:5CjabNRYYc57ZSkjA+JX2hxL9RB4iFbqHgo8lqKkddW8G/0YeaubqbUGppoRRM8G7mqMx4KnYJq4k2aDNy0S//n8jOICOjR6k5/BRmI0zYrbIbXK9y7IDJGl6lUcL31vSeYPXetB/eohdF8LargRIMOtC2aUv+AUjFmnUC9p+ts=,iv:xwG2sy4hCM6QLMZh7MpClwHSQDdphUl2I45xfDTht8E=,tag:OYMuenaiwuZxVRqrueU4zg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
