apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  annotations:
  name: renovate-github
  namespace: renovate-operator
spec:
  schedule: 0 * * * *
  discoveryFilter: nospamas/home-ops
  provider:
    name: github
  extraEnv:
    - name: RENOVATE_ALLOW_PLUGINS
      value: "true"
    # - name: RENOVATE_LOG_LEVEL
    #   value: debug
  image: ghcr.io/renovatebot/renovate:43.109.0
  parallelism: 5
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  secretRef: renovate-secret