kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: renovate-secret
stringData:
  GITHUB_COM_TOKEN: ENC[AES256_GCM,data:HIio8wcGpw5s4WRRh+/Jgxs9O7Rp9DASx7MMAsEZSZ6yTLLzjCjJWi+8DRsbPLTqX4pRtbDlH6srKVaJkMINWA2jxFnt9tDzp0EVu7hhzNnbaFYuJfkiXYEW1BVb,iv:sKSkb09jg8/mJoNiGCGP/cSe22KaH/g87tWW+SDaWHg=,tag:jr0G9wfNn6ZLxhv8lSIMSQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIaTU1UEl5dGQvQ2xqUk5Q
        dkNQUk9hUnJ1eVNXckx3cHFucy9CL3l2YkI0CkYzWXE2TFd0WW53ZEQ1VUhHMW5Y
        NTQ3TXNhQWwvYVdMYmJjTTBySFBWSWcKLS0tIHBIWG5QRnY5TGtjRFBPTUlGQVFn
        dVhGMS9KaUhhU2ZIcmJrOUN2dTBGY2sKgKUM10f+k3uaJ5hdyL9o2fKs/xgeF9YK
        mcWhYiJXXMFG2Ctst1a3CLUufnHetMz/18sfRsORT/1YetqW9VlP4A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sq0wjrxgd2p0kl55cl22306l3lyzt5n0hdmqny6tr9qfkwyxu3aszelc7a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-12T09:34:05Z"
  mac: ENC[AES256_GCM,data:2QjAPaKaGV9Mk1Eq7jaXYb33IpjeEGJ+SixwYk9PBd3qykDcKQiDnOe2nDgMxO4B8gooxQazj6kWdHqA2kyF8NzcJUJMnEmapiad1n6SLvOQBlm8tvtPjxqTXXkuwl4ct8jQfKh326+B8RGDPly+BrUjtD174k8alyuX+0q4mIM=,iv:0iXTh9NAsZkrQp1M6AU+RWiHpoHJyMwLTB8np/VXuWw=,tag:/MviBp69RIWhUPEYrWqSTw==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
