---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
components:
  - ../../components/common
resources:
  - ./longhorn/ks.yaml
  - ./openebs/ks.yaml
  - ./snapshot-controller/ks.yaml
  - ./volsync/ks.yaml
  - ./kopia/ks.yaml
patches:
  # privileged on namespace for Longhorn
  - patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: storage
        labels:
          pod-security.kubernetes.io/enforce: "privileged"
          pod-security.kubernetes.io/audit: "privileged"
          pod-security.kubernetes.io/warn: "privileged"
    target:
      kind: Namespace